### ISSUE TITLE
Critial error: Cannot find module...

### ISSUE THREAD

**Issue by Johnrobmiller** [gptlabs/nextjs-openai#1]
After installing the library, I went to go and use it but found that I could not. I cannot import anything from the library because of this error:

`Cannot find module 'nextjs-openai' or its corresponding type declarations.`

I did pretty much everything I could think of to make this error go away, including the obvious things like restarting vsc, deleting and reinstalling node_modules, etc. I also double checked this libs `package.json` to try to find the error there, but saw nothing.

This is a showstopper, as the library cannot be used at all until this error is fixed.

**Comment by ctjlewis** [comment]
Hey @Johnrobmiller, thanks for opening this, apparently I'd had the types messed up. That should be fixed on latest, please tag me if it's still broken:

```
yarn add nextjs-openai
```
