### ISSUE TITLE
done doesnt seem to change from true after rest call

### ISSUE THREAD

**Issue by madaher-dev** [gptlabs/nextjs-openai#10]
I am trying to save the buffer after done is true in a state as below:
 useEffect(() => {
    if (done) {
      setResult(buffer);
    }
  }, [done]);
But done seems to be stuck on true even after reset is triggered.
Lovely library. Would be happy to help if needed!

**Comment by aeneaswiener** [comment]
Had the same issue. Have you figured out a solution by any chance?

In nextjs, on initial page load it works as expected, with done set to false until the response is fully loaded. But then, if refresh is called done doesn't get reset to false, and is remain stuck on true, even though the rebuilding of the buffer works as expected.

**Comment by madaher-dev** [comment]
Hi,
I ended up using the library on the backend server only and on the front i parsed the data as follows:
```
const data = response.body;
      if (!data) {
        return;
      }
      const reader = data.getReader();
      const decoder = new TextDecoder();
      let done = false;
      let result = "";
      setLoading(2);
      while (!done) {
        const { value, done: doneReading } = await reader.read();
        done = doneReading;
        const chunkValue = decoder.decode(value);
        result += chunkValue;
        // setTemp(result);
        setBuffer((buffer) => [...buffer, chunkValue]);
      }

      if (done) {
      
        let fullStream = JSON.parse(result);
.....
```
Hope this helps

**Comment by aeneaswiener** [comment]
thanks

hmm i'm not a nextjs expert, but i wonder if we need to set done: false for the refresh case like i've done here https://github.com/aeneaswiener/nextjs-openai/blob/95382e87c3cc13883916e53c34dd3d1706eb1ee7/src/hooks/useBuffer/state.ts#L31 ?

Update: this appears to fix the issue

**Comment by ctjlewis** [comment]
This should be resolved.
