### ISSUE TITLE
Support Node <18

### ISSUE THREAD

**Issue by cooltaiwanesesam** [gptlabs/nextjs-openai#17]
On documentation mentioned Node <18 option, but got the error message during installation.

`nextjs-openai@7.1.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.19.0"`

I'm on Digital Ocean App Platform, and it does not support Node 18, what are the options to install this module with Node 16.X

**Comment by ctjlewis** [comment]
From the **Node <18** section:

```ts
import { OpenAI } from "openai-streams/node";
```

Does it still throw when you do that?

**Comment by ctjlewis** [comment]
Upgrade and let me know how it goes.

**Comment by cooltaiwanesesam** [comment]
With Node 16.X `yarn add nextjs-openai openai-streams` openai-streams installed fine, but nextjs-openai failed to install with the above original post error.

With Node 18.X, there is no issue to install, and run on localhost. However, I was not able to deploy to Digital Ocean as the nextjs-openai module is not supported as [Digital Ocean App Platform currently not supporting Node 18](https://www.digitalocean.com/community/questions/app-platform-when-will-node-18-be-supported).

**Comment by ctjlewis** [comment]
I set the engine to >=14 in that commit there, to match the streams lib, so it should work on latest.

**Comment by cooltaiwanesesam** [comment]
Look like the issue might be related to the '[yield-stream](https://www.npmjs.com/package/yield-stream)' module where by default it require Node 18+. For older version it need to import from `import { yieldStream } from "yield-stream/node";` according to the documentation.
https://github.com/SpellcraftAI/nextjs-openai/blob/canary/src/pages/api/node.ts#L4
