### ISSUE TITLE
Chat endpoint never sets `done` to true

### ISSUE THREAD

**Issue by elliotsayes** [gptlabs/nextjs-openai#6]
Not sure whether this more relates to `openai-streams` but `done` flag is never true when using a `chat` endpoint, even after output stops

as an aside it would be nice for StreamingText[Url] to have a built in onDone callback

```ts
export const ChatGPTCompleter: React.FC<Props> = ({url, data, onDone}: Props) => {  
  const { 
    buffer,
    done,
  } = useTextBuffer({
    url,
    data,
  });

  const parsedBuffer = buffer.map(parseChatGPTMessage);

  const [doneTriggered, setDoneTriggered] = useState(false);
  useEffect(() => {
    console.log(`done: ${done}, doneTriggered: ${doneTriggered}, parsedBuffer: ${parsedBuffer.join('')}`)
    if (done && !doneTriggered) {
      setDoneTriggered(true);
      onDone(parsedBuffer.join(''));
    }
  }, [done, doneTriggered, buffer, onDone]);

  return <StreamingText buffer={parsedBuffer} />
}
```

**Comment by ctjlewis** [comment]
Thanks for this, would welcome PR. Otherwise timeline probably 5-6 days.

**Comment by elliotsayes** [comment]
Happy to take a stab. Any guess where the issue might lie?

**Comment by ctjlewis** [comment]
Definitely this file is where I'd start: https://github.com/gptlabs/nextjs-openai/blob/d73ce08483ae86c0d232ee2842654dff4b62f891/src/hooks/useBuffer/index.ts#L106-L111

**Comment by ctjlewis** [comment]
It's likely something really silly in `state.ts` like the relevant action doesn't set `done: true` when it should:

https://github.com/gptlabs/nextjs-openai/blob/d73ce08483ae86c0d232ee2842654dff4b62f891/src/hooks/useBuffer/state.ts#L16-L50

<strike>Would be great if you add a test for it too, but if not I can do that part.</strike> Lmao just realized I didn't write tests for this library, don't worry about testing.

**Comment by ctjlewis** [comment]
Live in 3.0.8. I'll try to add that callback this week also.
